version: '3.6'

# make these services available to the network called "web"
networks:
  default:
    name: ${NETWORK}_default

services:
  www:
    build:
      context: www
      args:
        - NGINX_TAG=${NGINX_TAG}
    ports:
      - '80'
    volumes:
      - ./www/content:/usr/share/nginx/html/
      - ./www/init_content.sh:/docker-entrypoint.d/10-gwt-content.sh:ro
    environment:
      - BASE_DOMAIN=${BASE_DOMAIN}
      - VIRTUAL_HOST=${BASE_DOMAIN},www.${BASE_DOMAIN}
      - HSTS=off
      - LETSENCRYPT_HOST=${BASE_DOMAIN},www.${BASE_DOMAIN}
#  www-webhook:
#      image: thecatlady/webhook:2.8.0
#      volumes:
#        - ./www/hooks.json:/etc/webhook/hooks.json:ro
#        - ./www/init_content.sh:/init_content.sh:ro
#        - ./www/content/:/usr/share/nginx/html/
#      ports:
#        - '9000'
#      environment:
#        - VIRTUAL_HOST=webhook.www.${BASE_DOMAIN}
#        - LETSENCRYPT_HOST=webhook.www.${BASE_DOMAIN}
#        #      - GITHUB_TOKEN=${GITHUB_TOKEN}
#        - WEBHOOK_SECRET=${WEBHOOK_SECRET}
#      command: [ "-verbose", "-hooks=/etc/webhook/hooks.json", "-hotreload", "-template" ]

  static-samples:
    # Consider updating this to support dynamic samples in the future
    build:
      context: static-samples
      args:
        - NGINX_TAG=${NGINX_TAG}
        - GWT_DOWNLOAD=https://github.com/gwtproject/gwt/releases/download/2.12.1/gwt-2.12.1.zip
        - GWT_VERSION=2.12.1
    ports:
      - '80'
    environment:
      - VIRTUAL_HOST=samples.${BASE_DOMAIN}
      - HSTS=off
      - LETSENCRYPT_HOST=samples.${BASE_DOMAIN}
  plugins:
    image: nginx:${NGINX_TAG}
    ports:
      - '80'
    volumes:
      # Modify the existing default.conf file to allow directory listing for plugin versions
      - ./plugins/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./plugins/content:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=plugins.${BASE_DOMAIN}
      - HSTS=off
      - LETSENCRYPT_HOST=plugins.${BASE_DOMAIN}
  gwt-plugin-eclipse-nightly-update-webhook:
    image: thecatlady/webhook:2.8.0
    volumes:
      - ./plugins/hooks.json:/etc/webhook/hooks.json:ro
      - ./plugins/scripts:/scripts:ro
      - ./plugins/content/eclipse/gwt-eclipse-plugin:/plugins/gwt-eclipse-plugin/
      - ./plugins/content/eclipse/gwt-sdk-plugins:/plugins/gwt-sdk-plugins/
    ports:
      - '9000'
    environment:
      - VIRTUAL_HOST=webhook.plugins.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=webhook.plugins.${BASE_DOMAIN}
#      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    command: ["-verbose", "-hooks=/etc/webhook/hooks.json", "-hotreload", "-template"]
